In [ ]:
#Importing the libraries

import numpy as np

# Setting conversion rates and the number of samples
conversionRates = [0.15,0.04,0.13, 0.11, 0.05]              # predetermined to generate dataset
N = 10000
d = len(conversionRates)

# Creating the dataset

X = np.zeros((N, d))
for i in range (N):
  for j in range(d):
    if np.random.randn() < conversionRates[j]:
      X[i][j] = 1


print(X)
# Making array to count our wins and losses

nPosReward = np.zeros(d)
nNegReward = np.zeros(d)

# Taking our best slot machine through beta distribution and updating its losses and wins

for i in range(N):
  selected = 0
  maxRandom = 0
  for j in range(d):
    randomBeta = np.random.beta(nPosReward[j]+1, nNegReward[j] + 1)
    if randomBeta > maxRandom:
      maxRandom = randomBeta
      selected = j
# provide the feedback
  if X[i][selected] == 1:
    nPosReward[selected] += 1
  else:
    nNegReward[selected] += 1

# Showing which slot machine is considered the best

nSelected = nPosReward + nNegReward
for i in range(d):
  print('Machine number ' + str(i+1) + ' was selected ' + str(nSelected[i])+ ' times')
print('Conclusion : Best machine is machine number ' + str(np.argmax(nSelected) + 1 ))

[[1. 0. 1. 1. 1.]
 [1. 0. 1. 1. 1.]
 [1. 1. 1. 0. 1.]
 ...
 [0. 1. 1. 0. 0.]
 [0. 1. 0. 1. 1.]
 [1. 1. 0. 0. 1.]]
Machine number 1 was selected 2689.0 times
Machine number 2 was selected 628.0 times
Machine number 3 was selected 2771.0 times
Machine number 4 was selected 2581.0 times
Machine number 5 was selected 1331.0 times
Conclusion : Best machine is machine number 3
