In [11]:
# Predict which company will produce best returns based on their current expenditure and display in graph

# Import the libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#Import the dataset

dataset = pd.read_excel('Company.xlsx')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

# Apply One Hot Encoding on city i.e. column number 4

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer( transformers = [('encoder', OneHotEncoder(), [3])], remainder = 'passthrough')
X = np.array(ct.fit_transform(X))
print(X)

# Split the data into Training and Test set

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

[[0.0 1.0 0.0 165349 136897 471784]
 [0.0 0.0 1.0 162597 151377 443898]
 [1.0 0.0 0.0 153441 101145 407934]
 [0.0 1.0 0.0 144372 118671 383199]
 [1.0 0.0 0.0 142107 91391 366168]
 [0.0 1.0 0.0 131876 99814 362861]
 [0.0 0.0 1.0 134615 147198 127716]
 [1.0 0.0 0.0 130298 145530 323876]
 [0.0 1.0 0.0 120542 148718 311613]
 [0.0 0.0 1.0 123334 108679 304981]
 [1.0 0.0 0.0 101913 110594 229160]
 [0.0 0.0 1.0 100671 91790 249744]
 [1.0 0.0 0.0 93863 127320 249839]
 [0.0 0.0 1.0 91992 135495 252664]
 [1.0 0.0 0.0 119943 156547 256512]
 [0.0 1.0 0.0 114523 122616 261776]
 [0.0 0.0 1.0 78013 121597 264346]
 [0.0 1.0 0.0 94657 145077 282574]
 [1.0 0.0 0.0 91749 114175 294919]
 [0.0 1.0 0.0 86419 153514 0]
 [0.0 0.0 1.0 76253 113867 298664]
 [0.0 1.0 0.0 78389 153773 299737]
 [1.0 0.0 0.0 73994 122782 303319]
 [1.0 0.0 0.0 67532 105751 304768]
 [0.0 1.0 0.0 77044 99281 140574]
 [0.0 0.0 1.0 64664 139553 137962]
 [1.0 0.0 0.0 75328 144135 134050]
 [0.0 1.0 0.0 72107 127864 353183]
 [1.0 0.0 0.0 6

In [14]:
# Train the regressor on training set

from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

# Test the regressor on test set

y_pred = regressor.predict(X_test)
np.set_printoptions(precision= 2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))



[[103014.53 103282.  ]
 [132581.42 144259.  ]
 [132447.42 146121.  ]
 [ 71975.11  77798.  ]
 [178536.87 191050.  ]
 [116160.6  105008.  ]
 [ 67851.05  81229.  ]
 [ 98791.24  97483.  ]
 [113968.76 110352.  ]
 [167920.57 166187.  ]]
